### ISSUE TITLE
Error when building in vite app

### ISSUE THREAD

**Issue by yotamberk** [andreaswilli/react-verification-input#103]
First things firts, great module! 
I'm encountering a weird error. When building my app with `vite build`, the app crashes due to not managing to import this module since it is compiled to commonjs and not es-module.

**Comment by andreaswilli** [comment]
Thanks for the feedback.
I was able to reproduce the issue and I will look into it.

**Comment by bell-steven** [comment]
I opened PR #104 that should address this.

**Comment by yotamberk** [comment]
THANKS!

**Comment by andreaswilli** [comment]
Thanks @bell-steven for contributing!
I hope to find some time to look at it tonight.

**Comment by andreaswilli** [comment]
Released in version `3.1.3`
