### ISSUE TITLE
Needs ability to style the `vi__wrapper` div

### ISSUE THREAD

**Issue by reubennn** [andreaswilli/react-verification-input#114]
It would be great for additional props/add to the `classNames` prop so we can easily style `vi__wrapper`. e.g. I might want to center the verification input by applying `width: 100%`. I'm using SCSS modules so I want to avoid global styles. 

As a workaround, I can wrap `VerificationInput` in a div, then style it with:

```
display: flex;
justify-content: center;
```

**Comment by andreaswilli** [comment]
Could you give me a complete example of how you wanted to use the component to help me understand?

**Comment by arshaan-abh** [comment]
#118 This should solve this issue.

**Comment by andreaswilli** [comment]
Thanks @arshaan-abh 

I was thinking about getting rid of the wrapper div altogether. But I want to understand the problem before fixing it.

**Comment by arshaan-abh** [comment]
Of course. The wrapper has a `width: min-content`, which is hard to replace in Next.js, especially when using modular CSS.

**Comment by arshaan-abh** [comment]
I wanted to remove the tag too (in #118) but I thought there is a point to it which I don't understand, so I added an option to remove it optionally.

I could add an option to style the wrapper (by passing the `classNames`), but I thought it would be pointless since the wrapper doesn't do anything special.

**Comment by reubennn** [comment]
Exactly as I described. So vi_wrapper is the container class, and I wanted to style it (e.g. add `display: flex; justify-content: center;`). As a workaround, I had to create a wrapper over your wrapper just to implement the styles. This is counter-productive and would make more sense to be able to apply styles directly to the vi_wrapper instead.

**Comment by frixaco** [comment]
Any updates on this?

**Comment by laughingwhale1** [comment]
> Of course. The wrapper has a `width: min-content`, which is hard to replace in Next.js, especially when using modular CSS.

Had the same issue and solved it. Just add width to .vi__wrapper in global.css file (created by next.js by default) and that's it

**Comment by arshaan-abh** [comment]
> > Of course. The wrapper has a `width: min-content`, which is hard to replace in Next.js, especially when using modular CSS.
> 
> Had the same issue and solved it. Just add width to .vi__wrapper in global.css file (created by next.js by default) and that's it

True, but I don't think that this is a good practice, especially if you're using frameworks like Tailwind CSS.

**Comment by andreaswilli** [comment]
I removed the wrapper element and published it as `4.0.0-beta.1`. If someone can confirm this solves the problem, I'll create a regular release.

**Comment by alecananian** [comment]
@andreaswilli it looks great, thank you!

**Comment by andreaswilli** [comment]
Released in version `4.0.0`.
