### ISSUE TITLE
Can support the function of copying and pasting shortcut keys？

### ISSUE THREAD

**Issue by limuen** [andreaswilli/react-verification-input#117]
Want to use shortcut keys to copy, paste, and dynamically display it in input

**Comment by andreaswilli** [comment]
Pasting is already supported (as long as the clipboard content is a valid value).

As for copying: Did you want to copy the current value to clipboard?

And what do you mean by “dynamically display it in input“?

**Comment by limuen** [comment]
@andreaswilli Sorry, there was a mistake in expression. It was written perfectly. It has already started. Thank you
