### ISSUE TITLE
NextJs 15 installation error: some error in dependency tree

### ISSUE THREAD

**Issue by kunalmaloo77** [andreaswilli/react-verification-input#149]
Using Next.JS 15.0.1

![react-verification-input error](https://github.com/user-attachments/assets/97309e8b-b94d-4b93-ad84-344bbf4de947)

I think this package is not working in newer version of Next js 

This is debug.log file.

[2024-11-14T02_09_09_966Z-debug-0.log](https://github.com/user-attachments/files/17769669/2024-11-14T02_09_09_966Z-debug-0.log)

**Comment by andreaswilli** [comment]
Thanks for the report, fixed in `4.1.3`.
