### ISSUE TITLE
How do you retrieve the value?

### ISSUE THREAD

**Issue by jmxxii** [andreaswilli/react-verification-input#3]
Cannot find a way to retrieve the value of the input.

**Comment by jmxxii** [comment]
There is an input prop that is not mentioned in the docs.

`<VerificationInput 
  input={{
    onChange: (e) => this.setState({ value: e })
  }}
/>`

**Comment by leadream** [comment]
Maybe should expose onChange prop.

**Comment by andreaswilli** [comment]
`onChange` prop is now available in `v2.0.0`.
