### ISSUE TITLE
VerificationInput uses forwardRef but TS defs don't expose that

### ISSUE THREAD

**Issue by legraphista** [andreaswilli/react-verification-input#46]
Hi,

Thanks for the awesome component :smile:!

Unfortunately, I hit a little snag:

In your code, you expose the `ref` passthrough :tada: 
https://github.com/andreaswilli/react-verification-input/blob/acc512a822db1c8829fa9d83a4b5d48b5946f1aa/src/index.js#L9

But the definitions declare just a plain functional component
https://github.com/andreaswilli/react-verification-input/blob/acc512a822db1c8829fa9d83a4b5d48b5946f1aa/src/index.d.ts#L23

Could you please add the missing `ref` prop? or maybe make use of `PropsWithoutRef<P> & RefAttributes<T>` like here?
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/9cc04052f7e17abbfb2a8a1636ff9fa456b01552/types/react/index.d.ts#L805

I'm using the ref to listen to `paste` events so that I can remove dashes from the clipboard text since I want to ignore them.
For now, it's ok since I can `// @ts-ignore` it

**Comment by andreaswilli** [comment]
Thanks for the feedback.

I am not too familiar with React typings, but it seems like `PropsWithoutRef<P> & RefAttributes<T>` would be a good solution. I will take a closer look.

**Comment by legraphista** [comment]
Thanks for looking at it!

Since the props don't contain `ref` I think you can just append `& RefAttributes<T>` to them

**Comment by andreaswilli** [comment]
I decided to go with `ForwardRefExoticComponent` since this is how the `forwardRef` function is typed.

The change is released as version `2.0.1`. Let me know if it works for you.

Btw, do you think it would be a good idea to introduce a prop like:
```jsx
delimiterChars=" -_"
```
I'm asking since the component by default already ignores blanks when pasting a value.

**Comment by legraphista** [comment]
> Btw, do you think it would be a good idea to introduce a prop like:
> ```jsx
> delimiterChars=" -_"
> ```
> I'm asking since the component by default already ignores blanks when pasting a value.

Yes please, if you can!

**Comment by andreaswilli** [comment]
Another option would be to ignore everything that is not a valid character. I'm gonna give this some more thought.
