### ISSUE TITLE
Change input type?

### ISSUE THREAD

**Issue by centauruspool** [andreaswilli/react-verification-input#5]
Is there any way to change the input type?

Would be really helpful if we could change it to 'tel'.

`<input type="tel" />`

This means that on hybrid apps it would open the numeric keyboard which I believe it's a must.

Thanks!

**Comment by andreaswilli** [comment]
Everything from the `inputField` prop gets passed on to the input element.
So you can do this:
```jsx
<VerificationInput inputField={{ type: "tel" }} />
```
I hope this helps.

**Comment by centauruspool** [comment]
It works, thanks!
