### ISSUE TITLE
Manually selecting one of the fields

### ISSUE THREAD

**Issue by HazTheGoat** [andreaswilli/react-verification-input#88]
Hi,
Is it possible to select one of the fields by clicking it? As far as I have tested, it's only possible to get to the next field by filling out the previous one. This means that the user cannot enter a different value in the first field without backspacing and removing all the other values.

**Comment by andreaswilli** [comment]
Yes, that's correct. Individually selecting the fields was supported up to version `0.1.5` of the library.
However, it added a lot of complexity to the code, so I decided to drop this feature in version `2.0.0`.

If this is a must for you, maybe [react-code-input](https://github.com/40818419/react-code-input) or [react-pin-field](https://github.com/soywod/react-pin-field) is more suitable.
