### ISSUE TITLE
Can't type or paste this code: 008003

### ISSUE THREAD

**Issue by ntomkevich** [andreaswilli/react-verification-input#89]
can't type or paste codes starting with 00

**Comment by andreaswilli** [comment]
Please try to type or paste your code [here](https://andreaswilli.github.io/react-verification-input/) and let me know if it works.

If you want me to investigate this I'll need more information like what props are you using, what OS and browser, etc.

**Comment by ntomkevich** [comment]
@andreaswilli Yeah that one works fine.
